### ISSUE TITLE
issue on startup

### ISSUE THREAD

**Issue by ugurozpinar** [pritunl/pritunl-loader#1]
I have a droplet on digitalocean.ubuntu. Pritunl was perfect, then I restarted the server and it crashed. It couldnt connect the mongodb because mongodb stuck in startup.
My Solution : rm /var/lib/mongodb/mongod.lock

thanks

**Comment by zachhuff386** [comment]
What distribution and version are you using?

**Comment by ugurozpinar** [comment]
v1.0.482.93. Not development distribution if you ask that
